name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * 1'

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9
            runs-on: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Python 3.8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: py38

          - name: Python 3.7
            runs-on: ubuntu-latest
            python-version: 3.7
            toxenv: py37

          - name: Coverage
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: coverage

          - name: Code style checks
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: style

          - name: Bandit security audit
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: bandit

          - name: macOS
            runs-on: macos-latest
            python-version: 3.8
            toxenv: py38
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
      - name: Upload coverage to codecov
        if: ${{ contains(matrix.toxenv,'cov') }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  # Kept in a separate job because it needs extra system dependencies
  # that can't be installed by tox.
  # TODO: No documentation yet
  # build-docs:
  #   name: Build documentation and check warnings
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install system packages
  #       run: |
  #         sudo apt-get install graphviz texlive-latex-extra dvipng
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - name: Install tox
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install tox
  #     - name: Run tox
  #       run: tox -e build-docs
