name: Tag and release

on:
  workflow_dispatch:
    inputs:
      description:
        description: Release description (used as tag message and GitHub release body)
        required: true

jobs:
  release:
    name: Tag and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set changelog release date
        run: |
          scripts/set_release_date > version
          echo "::set-output name=version::$(cat version)"
        id: set_release_date

      - name: Commit changelog and tag release
        run: |
          git add CHANGES.rst
          git commit -m "Set ${{ steps.set_release_date.outputs.version }} release date"
          git push origin HEAD
          git tag -a ${{ steps.set_release_date.outputs.version }} -m "${{ github.event.inputs.description }}"
          git push origin ${{ steps.set_release_date.outputs.version }}

      - name: Create GitHub release (triggers publish-to-pypi workflow)
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: ${{ steps.set_release_date.outputs.version }}
          release_name: ${{ steps.set_release_date.outputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false

      - name: Create next changelog release section
        run: |
          scripts/insert_next_release > version
          echo "::set-output name=version::$(cat version)"
        id: insert_next_release

      - name: Commit changelog
        run: |
          git add CHANGES.rst
          git commit -m "Create ${{ steps.insert_next_release.outputs.version }} changelog section"
          git push origin HEAD
